### ISSUE TITLE
Resolve issue with fields labelUsed check when deleting & re-adding a field

### ISSUE THREAD

**Issue by stevenphaedonos** [moocunsw/ontask3_UNSW#144]

**Comment by JimmeeX** [comment]
Adding in a scenario for this (after an annoying amount of debugging)

A bug occurs on Create Datalab interface when:
1. Add Datasource & Choose Datasource
2. Set Primary Key to any column.
3. Click submit (after setting a datalab name)

Step 2 would incorrectly set the Datasource Module _labels_ attribute as _undefined_, when it should be set to include the name of the column. For example, if the column name is zid, setting the primary key would set label to be
`{'zid': undefined}` instead of the desired
`{'zid': zid}`.

This ultimately results in the server crashing when you try to view your datalab data.

A temporary fix in the UI around this is to add Fields first, then set the primary key last.

**Comment by dhphan95** [comment]
already fixed in #178
